name: Publish to PyPI

permissions:
  actions: write

on:
  workflow_run:
    workflows: [Python Tests]
    types:
    - completed
    branches:
    - main

jobs:
  pypi-release:
    name: PyPI Release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/graphomotor/

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

    - uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml

    - name: Skip release if version unchanged
      run: |
        version_change=$(git diff -r HEAD^1 pyproject.toml | grep -E "^(\+|-)version =")
        if [[ -z "$version_change" ]]; then
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: latest
        enable-cache: true

    - name: Build package
      run: uv build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
